apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - k8s/apps/webapp-service.yaml
  - k8s/apps/webapp-deployment.yaml
  - k8s/apps/webapp-ingress.yaml
  - k8s/apps/webapp-hpa.yaml
  - k8s/apps/traffic-deployment.yaml
