apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apache-tls
  namespace: apps
spec:
  secretName: apache-tls-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days before expiration
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - operating-systems.com
    - www.operating-systems.com
    - apache.apps.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
